# vim: ft=dockerfile
FROM tda283/tester

WORKDIR /home/user/

RUN dir="zig-linux-$(uname -m)-0.11.0-dev.1914+14590e956" && \
    file="$dir.tar.xz" && \
    curl -O "https://ziglang.org/builds/$file" && \
    tar -xf "$file" && rm "$file" && \
    mv "$dir" zig
ENV PATH="/home/user/zig/:${PATH}"

WORKDIR /home/user/tda283/tester
CMD /bin/bash
