# vim: ft=dockerfile
FROM tda283/tester

WORKDIR /home/user/

RUN file="kotlin-compiler-1.9.23" && \
    curl -LO "https://github.com/JetBrains/kotlin/releases/download/v1.9.23/$file.zip" && \
    unzip -d "$file" "$file.zip" && rm "$file.zip" && \
    mv "$file" kotlin
ENV PATH="/home/user/kotlin/kotlinc/bin:${PATH}"

WORKDIR /home/user/tda283/tester
CMD /bin/bash
