# vim: ft=dockerfile
FROM tda283/tester

WORKDIR /home/user/

USER root

RUN apt-get update
RUN apt-get install -y autoconf automake autotools-dev curl python3 python3-pip libmpc-dev libmpfr-dev libgmp-dev gawk build-essential bison flex texinfo gperf libtool patchutils bc zlib1g-dev libexpat-dev ninja-build git cmake libglib2.0-dev libslirp-dev

RUN git clone https://github.com/riscv/riscv-gnu-toolchain

WORKDIR /home/user/riscv-gnu-toolchain

RUN ./configure --prefix=/opt/riscv
RUN make linux

WORKDIR /home/user/

RUN apt-get install -y device-tree-compiler libboost-regex-dev libboost-all-dev
RUN git clone https://github.com/riscv-software-src/riscv-isa-sim.git

RUN mkdir /home/user/riscv-isa-sim/build
WORKDIR /home/user/riscv-isa-sim/build
RUN ../configure --prefix=/opt/riscv
RUN make
RUN make install

WORKDIR /home/user/

RUN curl -o qemu-9.0.0.tar.xz https://download.qemu.org/qemu-9.0.0.tar.xz
RUN tar xvJf qemu-9.0.0.tar.xz
WORKDIR /home/user/qemu-9.0.0
RUN ./configure
RUN make
RUN rm ../qemu-9.0.0.tar.xz

USER user
ENV PATH="/opt/riscv/bin/:/home/user/qemu-9.0.0/build/:${PATH}"
ENV QEMU_LD_PREFIX="/opt/riscv/sysroot"

WORKDIR /home/user/project/tester
CMD /bin/bash
