# vim: ft=dockerfile
FROM tda283/tester

WORKDIR /home/user/

RUN file="kotlin-native-linux-x86_64-1.8.10" && \
    curl -LO "https://github.com/JetBrains/kotlin/releases/download/v1.8.10/$file.tar.gz" && \
    tar -xzf "$file.tar.gz" && rm "$file.tar.gz" && \
    mv "$file" kotlin
ENV PATH="/home/user/kotlin/bin:${PATH}"

WORKDIR /home/user/tda283/tester
CMD /bin/bash
