# vim: ft=dockerfile
FROM tda283/tester

USER root

RUN apt install -y zlib1g-dev libncurses5-dev

USER user

RUN cabal install Agda

RUN curl -Lo ~/agda-stdlib.tar.gz https://github.com/agda/agda-stdlib/archive/refs/tags/v2.0.tar.gz
RUN cd ~ && tar -xzf agda-stdlib.tar.gz && rm agda-stdlib.tar.gz
RUN mkdir ~/.agda && echo "~/agda-stdlib-2.0/standard-library.agda-lib" >> ~/.agda/libraries

WORKDIR /home/user/tda283/tester
CMD /bin/bash
