# vim: ft=dockerfile
FROM tda283/tester

WORKDIR /home/user/

RUN dir="zig-$(uname -m)-linux-0.16.0-dev.2905+5d71e3051" && \
    file="$dir.tar.xz" && \
    curl -O "https://ziglang.org/builds/$file" && \
    tar -xf "$file" && rm "$file" && \
    mv "$dir" zig
ENV PATH="/home/user/zig/:${PATH}"

WORKDIR /home/user/project/tester
CMD /bin/bash
