# vim: ft=dockerfile
FROM tda283/tester

RUN curl https://sh.rustup.rs -sSf > rustup.sh && \
    sh rustup.sh -y && \
    $HOME/.cargo/bin/rustup toolchain install nightly && \
    $HOME/.cargo/bin/rustup default nightly && \
    rm rustup.sh

ENV PATH="/home/user/.cargo/bin:${PATH}"
WORKDIR /home/user/tda283/tester
CMD /bin/bash
